config/routes.rb
Rails.application.routes.draw do

  root 'events#index'

  resources :events do
    member do
      get :new_photo_for_event
    end
  end

  resources :photos do
    member do
      get :show_and_tag
    end
  end

  resources :tags
  resources :comments

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :commentable, polymorphic: true
end

app/models/event.rb
class Event < ActiveRecord::Base
	has_many :photos
	has_many :comments, as: :commentable
	accepts_nested_attributes_for :photos
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	belongs_to :event
	has_and_belongs_to_many :tags
	has_many :comments, as: :commentable
	mount_uploader :pic, PhotoUploader
	accepts_nested_attributes_for :comments
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_and_belongs_to_many :photos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@new_comment = Comment.new(comment_params)
		if @new_comment.save
			redirect_to events_path
		else
			render photo_path
		end
	end

	private

	def comment_params
		params.require(:comment).permit!
	end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	
	def index
		@events = Event.all
		@photos = Photo.all
	end

	def new
		@new_event = Event.new
		@new_event.photos.build
	end

	def create
		@new_event = Event.new(event_params)
		if @new_event.save
			redirect_to events_path
		else
			render new_event_path
		end
	end

	def new_photo_for_event			
		@event = Event.find(params[:id])
		@photo = @event.photos.build
	end

	def update
		@event = Event.find(params[:id])
		if @event.update_attributes(event_params)
			redirect_to events_path
		else
			render :back
		end
	end

	private

	def event_params
		params.require(:event).permit(:name, :description, :location, photos_attributes: [:pic, :event_id, :description], tags_attributes: [:name, :description])
	end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

	def new
		@new_photo = Photo.new
	end

	def create
		@new_photo = Photo.new(photo_params)
		if @new_photo.save
			redirect_to events_path
		else
			redirect_to new_photo_path
		end
	end

	def edit
		@photo = Photo.find(params[:id])
	end

	def show
		@photo = Photo.find(params[:id])
		@new_comment = @photo.comments.build
	end

	def show_and_tag
		@photo = Photo.find(params[:id])
		@new_tag = @photo.tags.build
	end

	private

	def photo_params
		params.require(:photo).permit(:pic, :event_id, :description, tags_attributes: [:name, :description])
	end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

	def new
		@tag = Tag.new
	end

	def create
		tag = Tag.where(name: params[:tag][:name]).first_or_create
		photo = Photo.find(params[:tag][:photo_id])
		photo.tags << tag
		if tag.save
			redirect_to events_path
		else
			render new_tag_path
		end
	end

	def edit
		@tag = Tag.find(params[:id])
	end

	private

	def tag_params
		params.require(:tag).permit!(:photo_id)
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/events/index.html.haml
.jumbotron
	%h2 Events
	= button_to "Add an event", new_event_path, method: :get

- @events.each do |event|
	.col-sm-3.col-xs-6
		.panel.panel-default
			.panel-thumbnail
				= button_to "Add a photo to this event", new_photo_for_event_event_path(event), method: :get
				Event:
				= event.name
				%br
				Location:
				= event.location
				%br
				Event Description:
				= event.description
				
				- event.photos.each do |photo|
					%br
					= image_tag photo.pic.url, width: 285, height: 285
					%br
					Photo Description:
					= photo.description
					%br
					Comments:
					
					- photo.comments.each do |comment| 
						= comment.content
						%br
						Tag:
					- photo.tags.uniq.each do |tag|
						= tag.name
					= button_to "Comment This Photo", photo_path(photo), method: :get
					= button_to "Tag This Photo", show_and_tag_photo_path(photo), method: :get
					%br

app/views/events/new.html.haml
= form_for @new_event do |e|
	Add An Event:
	= e.label "Event Name:"
	= e.text_field :name
	= e.label "Location"
	= e.text_field :location
	= e.label "Description"
	= e.text_field :description

	= e.fields_for :photos do |p|
		%br
		Add a picture:
		= p.file_field :pic
		Picture Description:
		= p.text_field :description
		= p.hidden_field :event_id, value: @new_event.id

	= e.submit "Add Item"

app/views/events/new_photo_for_event.html.haml
= form_for @photo do |f| 
	Event:
	= @event.name
	Add a picture:
	= f.file_field :pic
	Picture Description:
	= f.text_field :description
	= f.hidden_field :event_id, value: @event.id

	= f.submit "Add Photo"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PhotosAndEvents</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/photos/add_photo_to_event.html.haml
= fields_for @photo do |p| url: save_photo_to_event_photo, method: :post
	%br
	Add a picture:
	= p.file_field :pic
	Picture Description:
	= p.text_field :description

	= p.submit "Add Photo"

app/views/photos/edit.html.haml
= form_for @photo do |p|
	= image_tag @photo.pic.url, width: 200, height: 200
	= p.label "Tag this photo"
	= p.text_field 

app/views/photos/get_tag.html.haml
= form_for @photo do |p|
	= image_tag @photo.pic.url, width: 200, height: 200
	
	= p.fields_for :tags do |t|
		= t.label "Tag this photo"
		= t.text_field :description
	= p.submit "Tag"

app/views/photos/new.html.haml
= form_for @new_photo do |p|
	Add a picture:
	= p.file_field :pic
	Picture Description:
	= p.text_field :description
	= p.hidden_field :event_id, value: params[:id]

app/views/photos/show.html.haml
= form_for @new_comment do |p|
	= image_tag @photo.pic.url, width: 200, height: 200
	= p.label "Comment this photo"
	= p.hidden_field :commentable_id, value: @new_comment.commentable_id
	= p.hidden_field :commentable_type, value: @new_comment.commentable_type
	= p.text_field :content
	= p.submit "Add Comment"

app/views/photos/show_and_tag.html.haml
= form_for @new_tag do |p|
	= image_tag @photo.pic.url, width: 200, height: 200
	= p.label "Tag this photo"
	= p.text_field :name
	= p.hidden_field :photo_id, value: @photo.id
	= p.submit "TAG"
	%br
	%br
	Tagged as:
	- @photo.tags.uniq.each do |tag|
		= tag.name

app/views/tags/edit.html.haml
= form_for @tag do |t|
	= image_tag @tag.photo.pic.url, width: 200, height: 200
	= p.label "Tag this photo" 
	= p.text_field 

app/views/welcome/index.html.haml
index.html.haml